# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DrillHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'somewhere'), (2, 'bin'), (3, 'lab')], default=1)),
                ('time_created', models.DateTimeField(default=datetime.datetime(2016, 3, 4, 23, 32, 33, 786662, tzinfo=utc))),
                ('last_modified', models.DateTimeField(default=datetime.datetime(2016, 3, 4, 23, 32, 33, 786662, tzinfo=utc))),
                ('current_geo', geoposition.fields.GeopositionField(max_length=42, null=True)),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Bin')),
                ('drillhole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.DrillHole')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Lab')),
            ],
        ),
        migrations.AddField(
            model_name='drillhole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.Project'),
        ),
    ]
