# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0002_auto_20160305_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='sample',
            name='tag',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.Sample'),
        ),
    ]
