# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0003_auto_20160305_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Bin'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Lab'),
        ),
    ]
