# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('st', '0004_auto_20160305_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Bin'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='geo',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='st.Lab'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='status',
            field=models.IntegerField(choices=[(1, 'somewhere'), (2, 'bin'), (3, 'lab')], default=1),
        ),
        migrations.AddField(
            model_name='logentry',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
